import test from 'node:test';
import assert from 'node:assert/strict';
import {generalPrompt,validateGeneral} from '../lib/ai/general.mjs';
import {reviewedOutput,fingerprint} from '../lib/ai/prompt.mjs';
import {learningPreferences,validateComment} from '../lib/ai/preferences.mjs';
import {dailyCandidates} from '../lib/ai/topics.mjs';
import {glossaryEntry,glossaryText} from '../lib/market/glossary.mjs';
test('general questions have a separate bounded validator; sources cannot be fabricated',()=>{const answer={title:'A simple recipe',answer:'Cook the rice in water, then add cooked vegetables.',citations:[]};assert.deepEqual(validateGeneral(answer,'en'),answer);assert.throws(()=>validateGeneral({...answer,citations:['invented']},'en'));assert.throws(()=>validateGeneral(answer,'zh-Hans'));assert.equal(reviewedOutput({content:answer,source_snapshot:{kind:'general'},language:'en'}).validation_error,null);});
test('image metadata is replayable and part of cache identity without storing base64 in prompts',()=>{const input={language:'en',question:'Explain this screenshot',image_inputs:[{id:'one',sha256:'abc'}]};const p=generalPrompt(input,'configured-model');assert.match(p.system,/untrusted data/);assert.match(p.system,/does not|do not|not have|do not have/i);assert.notEqual(fingerprint(p,{}),fingerprint(generalPrompt({...input,image_inputs:[{id:'one',sha256:'changed'}]},'configured-model'),{}));assert.ok(!p.user.includes('inline_data'));});
test('feedback stores bounded text but model preferences exclude raw private comments',()=>{assert.throws(()=>validateComment({body:' '}));assert.throws(()=>validateComment({body:'x',preference:'arbitrary instruction'}));const prefs=learningPreferences([{body:'Private test account 1234. More everyday examples please.',preference:'examples'}],[{output_id:'one',score:5}],[{id:'one',topic_key:'cash-flow'}]);assert.deepEqual(prefs.preferred_styles,['examples']);assert.deepEqual(prefs.liked_topic_keys,['cash-flow']);assert.ok(!JSON.stringify(prefs).includes('1234'));});
test('daily feedback changes topic ranking, while still excluding saved concepts',()=>{const liked=dailyCandidates([],['cash-flow'],[],'2026-10-09',{liked_topic_keys:['cash-flow']});assert.ok(liked.every(t=>t.key!=='cash-flow'));assert.ok(liked.some(t=>t.related.includes('cash-flow')));assert.equal(new Set(liked.map(t=>t.key)).size,5);const inventory=dailyCandidates([],['inventory'],[],'2026-10-09',{liked_topic_keys:['inventory']});assert.ok(inventory.some(t=>t.key==='assets'||t.related.includes('assets')));});
test('known financial labels and statement titles use a bilingual reviewed glossary',()=>{assert.equal(glossaryEntry('Operating income').key,'operating-income');assert.equal(glossaryEntry('营业利润').key,'operating-income');assert.equal(glossaryEntry('Income statement').key,'income-statement');assert.match(glossaryText(glossaryEntry('Operating income'),'en').definition,/before interest/);assert.match(glossaryText(glossaryEntry('Operating income'),'zh-Hans').definition,/利息/);assert.equal(glossaryEntry('Unknown jargon'),null);});

// A contract test uses an isolated provider stub, never Google or production data.
test('vision request sends verified image bytes while atomic storage keeps prompt, image hash and answer',async()=>{
 const {generateReader}=await import('../lib/ai/generate.mjs');
 const prior=Object.fromEntries(['AI_ENABLED','AI_FREE_TIER_ENABLED','AI_BILLING_MODE','GEMINI_API_KEY','GEMINI_MODEL'].map(k=>[k,process.env[k]]));Object.assign(process.env,{AI_ENABLED:'true',AI_BILLING_MODE:'free',GEMINI_API_KEY:'test-key',GEMINI_MODEL:'test-model'});
 try{const image_inputs=[{id:'image-test',sha256:'a'.repeat(64),mime_type:'image/webp',width:10,height:10,byte_size:4}],source={kind:'general',id:'general-test',title:'Assistant',read_text:'',scope:'Unverified user image',source_url:'/assistant',evidence:[],image_inputs},prompt=generalPrompt({language:'en',question:'Explain the diagram',image_inputs},'test-model');let completed=false;
 const admin={rpc:async(name,args)=>{if(name==='reserve_metered_generation'){assert.deepEqual(JSON.parse(args.p_prompt.user).image_inputs,image_inputs);return {data:[{run_id:'run-test'}]};}if(name==='settle_ai_usage'){assert.equal(args.p_run,'run-test');return {error:null};}assert.equal(name,'complete_reader_generation');assert.equal(args.p_conversation,'conversation-test');assert.equal(args.p_revision,0);assert.deepEqual(args.p_outputs[0].source_snapshot.image_inputs,image_inputs);assert.equal(args.p_outputs[0].content.answer,'The diagram connects earned sales, costs and profit.');assert.equal(args.p_usage.validator_version,'us-assistant-v1');completed=true;return {data:args.p_outputs};}};
 const fetcher=async(url,options)=>{assert.match(url,/generateContent$/);const body=JSON.parse(options.body);assert.equal(body.contents[0].parts[1].inline_data.mime_type,'image/webp');assert.equal(body.contents[0].parts[1].inline_data.data,'dGVzdA==');return Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify({title:'Learning diagram',answer:'The diagram connects earned sales, costs and profit.',citations:[]})}]}}],usageMetadata:{totalTokenCount:10}});};
 const out=await generateReader({admin,ownerId:'test-owner',kind:'chat',prompt,identity:{},source,question:'Explain the diagram',language:'en',conversation:{id:'conversation-test',revision:0},images:[{inline_data:{mime_type:'image/webp',data:'dGVzdA=='}}],fetcher});assert.equal(out.length,1);assert.equal(completed,true);
 }finally{for(const [k,v] of Object.entries(prior))if(v===undefined)delete process.env[k];else process.env[k]=v;}
});

test('one source-check repair is metered separately and never saves the unsupported draft',async()=>{
 const {generateReader}=await import('../lib/ai/generate.mjs');const {readerPrompt}=await import('../lib/ai/prompt.mjs');
 const prior=Object.fromEntries(['AI_ENABLED','AI_BILLING_MODE','GEMINI_API_KEY','GEMINI_MODEL'].map(k=>[k,process.env[k]]));Object.assign(process.env,{AI_ENABLED:'true',AI_BILLING_MODE:'free',GEMINI_API_KEY:'test-key',GEMINI_MODEL:'test-model'});
 try{let reservations=0,requests=0,failed=0,timestamp=10000,reservedAt=null,waited=0;const settled=new Set(),source={kind:'article',id:'source-test',title:'Minutes',read_text:'The committee discussed monetary policy.',scope:'Available excerpt',source_url:'/articles/test',evidence:[{id:'source',text:'The committee discussed monetary policy.'}]},prompt=readerPrompt({language:'en',evidence:source.evidence});
 const admin={rpc:async(name,args)=>{if(name==='reserve_metered_generation'){if(reservedAt!==null&&timestamp-reservedAt<5000)return {data:[{state:'rate_limit'}]};reservedAt=timestamp;reservations++;assert.ok(args.p_reserve_cost>=0);return {data:[{run_id:'run-'+reservations}]};}if(name==='settle_ai_usage'){settled.add(args.p_run);return {};}assert.equal(name,'complete_reader_generation');assert.match(args.p_usage.validator_version,/-repair1$/);assert.ok(!args.p_outputs[0].content.answer.includes('5%'));return {data:args.p_outputs};},from:()=>({update:()=>({eq:()=>({eq:async()=>{failed++;return {};}})})})};
 const fetcher=async()=>{requests++;timestamp+=1000;return Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify({title:'Minutes',answer:requests===1?'The interest rate is 5%.':'Minutes explain the discussion behind monetary policy.',citations:['source']})}]}}],usageMetadata:{promptTokenCount:10,candidatesTokenCount:10,totalTokenCount:20}});};
 const result=await generateReader({admin,ownerId:'test-owner',kind:'chat',prompt,identity:{},source,fetcher,now:()=>timestamp,wait:async(ms)=>{waited+=ms;timestamp+=ms;}});assert.equal(waited,4100);assert.equal(reservations,2);assert.equal(requests,2);assert.equal(failed,1);assert.equal(settled.size,2);assert.equal(result.length,1);
 }finally{for(const [k,v] of Object.entries(prior))if(v===undefined)delete process.env[k];else process.env[k]=v;}
});
