import test from 'node:test';
import assert from 'node:assert/strict';
import {readerPrompt,fingerprint,selectedInSource,validateReader,validateDaily,matchesLanguage} from '../lib/ai/prompt.mjs';
import {dailyCandidates,topics,noteTopicKeys} from '../lib/ai/topics.mjs';
const evidence=[{id:'filing',text:'Costco operated 939 warehouses. Revenue was 303154000000 USD.'}];
test('selected phrases must exist in the server-resolved article; forged text and oversized selections fail',()=>{assert.equal(selectedInSource('939 warehouses',{read_text:'Operated  939   warehouses.'}),'939 warehouses');assert.throws(()=>selectedInSource('invented claim',{read_text:'939 warehouses'}));assert.throws(()=>selectedInSource('a'.repeat(161),{read_text:'a'.repeat(200)}));});
test('source citations and exact numbers are checked; length caps apply to short AI explanations',()=>{assert.equal(validateReader({title:'Warehouses',answer:'The source reports 939 warehouses.',citations:['filing']},evidence,{brief:true}).citations[0],'filing');assert.throws(()=>validateReader({title:'Warehouses',answer:'1,000 warehouses.',citations:['filing']},evidence));assert.throws(()=>validateReader({title:'x',answer:'x',citations:['fake']},evidence));assert.throws(()=>validateReader({title:'x',answer:'word '.repeat(201),citations:['filing']},evidence,{brief:true}));assert.throws(()=>validateReader({title:'x',answer:'字'.repeat(601),citations:['filing']},evidence,{brief:true,language:'zh-Hans'}));});
test('prompts and cache fingerprints reproduce exactly; language, mode, source and model changes invalidate short-answer cache',()=>{const input={mode:'explain',language:'en',evidence};const p=readerPrompt(input,{brief:true,model:'configured-model'});assert.equal(fingerprint(p,{ownerId:'A'}),fingerprint(readerPrompt(input,{brief:true,model:'configured-model'}),{ownerId:'A'}));for(const alt of [{...input,language:'zh-Hans'},{...input,mode:'translate'},{...input,evidence:[{id:'different',text:'Changed'}]}])assert.notEqual(fingerprint(p,{}),fingerprint(readerPrompt(alt,{brief:true,model:'configured-model'}),{}));assert.notEqual(fingerprint(p,{ownerId:'A'}),fingerprint(p,{ownerId:'B'}));assert.match(p.system,/untrusted DATA/);assert.equal(p.prompt_version,'us-reader-v10');});
test('daily candidates exclude saved terms and starred topics and contain five distinct supported topics',()=>{const c=dailyCandidates([{source_key:'concept:stock',text:'A stock'},{text:'Net income'}],['balance-sheet'],[],'2026-10-08');assert.equal(c.length,5);assert.equal(new Set(c.map(t=>t.key)).size,5);assert.ok(c.every(t=>!['stock','net-income','balance-sheet'].includes(t.key)&&t.source.startsWith('https://')));assert.deepEqual(c,dailyCandidates([{source_key:'concept:stock',text:'A stock'},{text:'Net income'}],['balance-sheet'],[],'2026-10-08'));});
test('daily response must contain exactly the supplied five topics, each cited to its own evidence',()=>{const c=dailyCandidates([],[],[],'2026-10-08');const v={lessons:c.map(t=>({topic_key:t.key,title:t.term,answer:t.definition,citations:[t.key]}))};assert.equal(validateDaily(v,c,'en').length,5);assert.throws(()=>validateDaily({lessons:v.lessons.slice(0,4)},c,'en'));assert.throws(()=>validateDaily({lessons:[v.lessons[0],...v.lessons.slice(0,4)]},c,'en'));assert.equal(topics.length,33);});

test('private note profiling sends allowlisted topics rather than raw titles, bodies or numbers',()=>{const keys=noteTopicKeys([{title:'Private thoughts',body:'Cash flow and 净利润. My confidential account is 123456.'}]);assert.ok(keys.includes('cash-flow')&&keys.includes('net-income'));assert.ok(keys.every(k=>topics.some(t=>t.key===k)));assert.ok(!JSON.stringify(keys).includes('123456'));});

test('responses must match the requested language, including Chinese explanations of English sources',()=>{assert.throws(()=>validateReader({title:'Warehouses',answer:'The source reports 939 warehouses.',citations:['filing']},evidence,{brief:true,language:'zh-Hans'}));assert.equal(validateReader({title:'仓库数量',answer:'原文指的是企业运营的仓库总数，其中共有939座仓库。',citations:['filing']},evidence,{brief:true,language:'zh-Hans'}).citations[0],'filing');});

test('full dates and reporting periods are checked as units, not just individually valid digits',()=>{const e=[{id:'financial',text:'Annual period 2025-09-01 to 2026-08-30. Costco operated 939 warehouses at August 30, 2026.'}];assert.throws(()=>validateReader({title:'Report',answer:'Annual period 2026-09-01 to 2026-08-30.',citations:['financial']},e));assert.equal(validateReader({title:'财报',answer:'截至2026年8月30日，该公司运营939座仓库。',citations:['financial']},e,{language:'zh-Hans'}).citations[0],'financial');});

test('Chinese translation rejects mostly untranslated English finance phrases',()=>{assert.equal(matchesLanguage('库存是什么？gross margins sales volumes rapid inventory turnover risks and uncertainties','zh-Hans'),false);assert.equal(matchesLanguage('Costco通过减少库存商品种类，加快销售和补货。营业收入并不等于实际收到的现金。','zh-Hans'),true);});

test('SEC non-affiliate shareholders are not misrepresented as a separate registrant',()=>{const e=[{id:'filing',text:'Stock held by non-affiliates of the registrant.'}];assert.throws(()=>validateReader({title:'股东',answer:'非关联方注册人持有的有表决权股票。',citations:['filing']},e,{language:'zh-Hans'}));assert.doesNotThrow(()=>validateReader({title:'股东',answer:'这指的是与申报公司没有关联关系的股东持有的该公司的股票。',citations:['filing']},e,{language:'zh-Hans'}));});

test('Chinese explanations distinguish absolute gross profit from a margin rate',()=>{const ev=[{id:'source',text:'Gross profit is revenue less cost of goods; a gross margin rate divides gross profit by revenue.'}];assert.throws(()=>validateReader({title:'毛利率',answer:'毛利率（净销售额减去商品成本）可以比较公司。',citations:['source']},ev,{language:'zh-Hans'}));assert.doesNotThrow(()=>validateReader({title:'毛利与毛利率',answer:'毛利是销售收入减去商品成本。毛利率则是毛利除以销售收入。',citations:['source']},ev,{language:'zh-Hans'}));});

test('current IEX trade and retrieved passages cannot be relabeled as close or missing original',()=>{const ev=[{id:'market-snapshot',text:'Latest observed IEX trade: 947.68 USD.'},{id:'filing-part-1',text:'Relevant passages from full original cached.'}];assert.throws(()=>validateReader({title:'市场',answer:'最新数据的收盘价为947.68 USD。',citations:['market-snapshot']},ev,{language:'zh-Hans'}));assert.throws(()=>validateReader({title:'资料',answer:'本报告仅提供部分SEC文件节选。',citations:['filing-part-1']},ev,{language:'zh-Hans'}));assert.doesNotThrow(()=>validateReader({title:'资料',answer:'原文已完整缓存，本次解释依据检索出的相关段落。最近成交价为947.68 USD。',citations:['filing-part-1','market-snapshot']},ev,{language:'zh-Hans'}));});

test('list numbering is formatting but invented financial amounts remain rejected',()=>{const ev=[{id:'source',text:'The committee discussed monetary policy.'}];assert.doesNotThrow(()=>validateReader({title:'Minutes',answer:'1. Minutes describe the discussion.\n2. They explain the thinking behind policy.',citations:['source']},ev));assert.throws(()=>validateReader({title:'Minutes',answer:'1. The interest rate is 5%.',citations:['source']},ev));});

test('English meeting date ranges translate as whole dates without inventing reporting periods',()=>{const ev=[{id:'source',text:'Minutes of the committee, September 15-16, 2026.'}];assert.doesNotThrow(()=>validateReader({title:'会议纪要',answer:'这是2026年9月15日至16日的委员会会议纪要。',citations:['source']},ev,{language:'zh-Hans'}));assert.throws(()=>validateReader({title:'会议纪要',answer:'这是2026年9月17日的委员会会议纪要。',citations:['source']},ev,{language:'zh-Hans'}));assert.throws(()=>validateReader({title:'Minutes',answer:'The rate was 9%.',citations:['source']},ev));});
