import {normalizeFilingText} from './validation.mjs';
import {linkedMinutesUrl} from './public-article.mjs';
export function validOriginalUrl(value){return /^(?:https:\/\/www\.federalreserve\.gov\/(?:newsevents\/pressreleases\/[a-z0-9]+\.htm|monetarypolicy\/fomcminutes\d{8}\.htm)|https:\/\/www\.bea\.gov\/news\/\d{4}\/[a-z0-9-]+|https:\/\/www\.bls\.gov\/news\.release\/[a-z0-9_.-]+\.htm)$/i.test(value||'');}
function fieldBody(html,name){const match=new RegExp('<div\\b[^>]*class=[\"\'][^\"\']*\\bfield--name-'+name+'\\b[^\"\']*[\"\'][^>]*>','i').exec(html);if(!match)return '';const at=match.index,tags=/<\/?div\b[^>]*>/gi;tags.lastIndex=at;let depth=0;for(let tag; (tag=tags.exec(html));){depth+=tag[0].startsWith('</')?-1:1;if(!depth)return html.slice(at,tags.lastIndex);}return '';}
export function originalHtmlText(html,source){
 let body='';
 if(source==='Federal Reserve'){const at=html.search(/<(?:div|article)\b[^>]*\bid=["']article["']/i);if(at>=0)body=html.slice(at).split(/<footer\b|<div\b[^>]*\bid=["']footer["']/i)[0];}
 if(source==='BEA'){const match=html.match(/<article\b[^>]*>[\s\S]*?<\/article>/i);const article=match?.[0]||'';const main=fieldBody(article,'body');body=main?[main,fieldBody(article,'field-additional-information')].filter(Boolean).join('\n'):article;}
 if(source==='BLS'){const at=html.search(/<div\b[^>]*\bid=["']bodytext["']/i);if(at>=0)body=html.slice(at).split(/<footer\b|<div\b[^>]*\bid=["']bls-footer/i)[0];}
 return body.replaceAll('&ldquo;','“').replaceAll('&rdquo;','”').replaceAll('&lsquo;','‘').replaceAll('&rsquo;','’').replaceAll('&ndash;','–').replaceAll('&mdash;','—').replace(/<(script|style|nav)\b[^>]*>[\s\S]*?<\/\1>/gi,'').split(/<\/(?:p|h[1-6]|li|tr|section)>/i).map(block=>normalizeFilingText(block,1000000)).filter(Boolean).join('\n\n').slice(0,1000000);
}
async function htmlAt(url){const response=await fetch(url,{redirect:'error',signal:AbortSignal.timeout(6000),next:{revalidate:3600}});if(!response.ok||!response.headers.get('content-type')?.includes('text/html'))return null;const reader=response.body.getReader(),chunks=[];let length=0;for(;;){const {done,value}=await reader.read();if(done)break;length+=value.length;if(length>3000000){await reader.cancel();return null;}chunks.push(value);}return Buffer.concat(chunks).toString('utf8');}
export async function officialOriginal(url,source){if(!validOriginalUrl(url)||!({'Federal Reserve':'www.federalreserve.gov',BEA:'www.bea.gov',BLS:'www.bls.gov'})[source]||new URL(url).hostname!==({'Federal Reserve':'www.federalreserve.gov',BEA:'www.bea.gov',BLS:'www.bls.gov'})[source])return null;try{let html=await htmlAt(url);if(!html)return null;const minutes=source==='Federal Reserve'?linkedMinutesUrl(html):null;if(minutes&&minutes!==url){const linked=await htmlAt(minutes);if(linked){url=minutes;html=linked;}}
 const text=originalHtmlText(html,source);return text.length>=200?{text,url}:null;}catch{return null;}}
// Anchor the selected sentence even when it lies far beyond the first model excerpt.
export function readingPassage(text,query='',budget=12000){const normalized=text.replace(/\s+/g,' ').trim(),needle=String(query).replace(/\s+/g,' ').trim(),at=needle?normalized.toLowerCase().indexOf(needle.toLowerCase()):-1;const start=at>=0?Math.max(0,at-Math.floor(budget/3)):0;return normalized.slice(start,start+budget);}
export function originalPage(text,part=1,budget=16000){const chunks=[];let start=0;while(start<text.length){let end=Math.min(start+budget,text.length);if(end<text.length){const boundary=text.lastIndexOf(' ',end);if(boundary>start+budget/2)end=boundary;}chunks.push(text.slice(start,end).trim());start=end+1;}const page=Math.max(1,Math.min(chunks.length,parseInt(String(part))||1));return {text:chunks[page-1]||'',page,total:chunks.length};}

export function readingParagraphs(text){if(text.includes('\n\n'))return text.split(/\n\s*\n/);const paragraphs=[];let at=0;while(at<text.length){let end=Math.min(at+1000,text.length);if(end<text.length){const sentence=text.lastIndexOf('. ',end),space=text.lastIndexOf(' ',end);end=sentence>at+350?sentence+1:space>at?space:end;}paragraphs.push(text.slice(at,end).trim());at=end+1;}return paragraphs;}
