import Image from "next/image";
import { createClient } from "@/lib/supabase/server";
import { HumorStudio, VoteButtons } from "@/components/humor-studio";
export const dynamic="force-dynamic";
export default async function Home(){
 const db=await createClient();const {data:{user}}=await db.auth.getUser();
 const {data:images,error}=user?await db.from("humor_images").select("id,storage_path,description,humor_captions(id,content)").eq("status","ready").order("created_at",{ascending:false}).limit(24):{data:null,error:null};
 const {data:votes}=user?await db.from("humor_votes").select("caption_id,value").eq("user_id",user.id):{data:null};
 const photos=await Promise.all((images||[]).map(async i=>{const {data}=await db.storage.from("humor-images").createSignedUrl(i.storage_path,3600);return {...i,url:data?.signedUrl};}));
 return <><section className="humor-hero"><span className="eyebrow">THE INTERNET COULD USE A GOOD LAUGH</span><h1>Small moments.<br/><span>Big caption energy.</span></h1><p>Turn your camera roll into a comedy club. Make captions with AI, then tell us which ones actually land.</p><a className="button" href="#studio">Find your funny ↓</a><div className="hero-stamp" aria-hidden="true">ha<span>ha.</span><small>YOUR DAILY DOSE OF ABSURD</small></div></section><HumorStudio signedIn={!!user}/><section id="gallery"><div className="section-title"><div><span className="eyebrow">02 / THE LAUGH LAB</span><h2>The audience has the last word.</h2></div><span className="pill">One vote. Honest taste.</span></div><p>Four takes on every photo. Pick the punchlines that deserve an encore.</p>{!user?<div className="panel"><h3>The club is open. Come on in.</h3><p>Sign in to see member photos, create captions and cast your votes.</p><a className="text-link" href="/login">Join the laugh lab ↗</a></div>:error?<div className="panel" role="alert">The gallery is temporarily unavailable. Please try again later.</div>:!photos.length?<div className="panel"><h3>Every comedy club starts with an opening act.</h3><p>Upload the first photo and give everyone something to laugh about.</p></div>:<div className="humor-grid">{photos.map(i=><article className="humor-card panel" key={i.id}>{i.url?<Image unoptimized src={i.url} alt={i.description||"Member uploaded photo"} width={600} height={420}/>:<p>Photo temporarily unavailable.</p>}<div className="caption-list">{i.humor_captions.map((c,n)=><div className="caption-item" key={c.id}><span className="eyebrow">TAKE 0{n+1}</span><p>{c.content}</p><VoteButtons captionId={c.id} vote={votes?.find(v=>v.caption_id===c.id)?.value??null}/></div>)}</div></article>)}</div>}</section></>;
}
