'use client';
import {useLanguage} from "@/components/language-provider";

import {T} from "@/components/language-provider";

import {useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
const levels=[[1,'😕','Not useful'],[2,'🤔','Still unclear'],[3,'🙂','Somewhat useful'],[4,'💡','Useful'],[5,'🤩','Very useful']] as const;
export function AIRating({outputId,initial=null}:{outputId:string;initial?:number|null}){
 const {t:ui}=useLanguage();const [open,setOpen]=useState(false),[score,setScore]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState('');return <div className="ai-rating"><button type="button" className="rating-plus" aria-label={ui("Rate this AI answer")} aria-expanded={open} onClick={()=>setOpen(!open)}>＋ <span>{score?`${score}/5`:<T text="Rate"/>}</span></button>{open&&<div className="ai-rating-options"><p className="small"><T text="How much did this help you understand?"/></p><div className="ai-emoji-row" role="group" aria-label={ui("AI usefulness rating")}>{levels.map(([n,emoji,label])=><button type="button" key={n} disabled={busy} aria-pressed={score===n} aria-label={`${n}/5 — ${ui(label)}`} title={ui(label)} onClick={async()=>{setBusy(true);setError('');try{const r=await fetch('/api/ai/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({output_id:outputId,score:n})});const d=await r.json();if(!r.ok)throw new Error(d.error);setScore(n);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{emoji}<small>{n}</small></button>)}</div><p className="small" role="status">{busy?<T text="Saving…"/>:score?ui(`Rating saved: ${score}/5. You can change it.`):<T text="Tap an emoji to save your rating."/>}</p>{error&&<p className="small" role="alert">{ui(error)}</p>}</div>}</div>;}
export function AISave({id,kind,initial=false,onSaved}:{id:string;kind:'term'|'chat'|'lesson';initial?:boolean;onSaved?:(saved:boolean)=>void}){
 const {t:ui}=useLanguage();const router=useRouter();const [saved,setSaved]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState('');const label=kind==='lesson'?'article':kind==='chat'?'conversation':'term';return <span className="ai-save-control"><button type="button" className={'ai-star '+(saved?'selected':'')} aria-pressed={saved} aria-label={ui((saved?'Unsave ':'Save ')+label)} disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const r=await fetch('/api/ai/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,kind,saved:!saved})}),d=await r.json();if(!r.ok)throw new Error(d.error);setSaved(d.saved);onSaved?.(d.saved);if(kind==='chat'&&!d.saved)router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><span aria-hidden="true">{saved?'★':'☆'}</span> {busy?<T text="Saving…"/>:saved?<T text="In Notebook"/>:<T text="Save to Notebook"/>}</button>{saved&&<Link className="small" href={'/notebook?kind='+(kind==='lesson'?'lessons':kind==='chat'?'chats':'terms')}><T text="Notebook ↗"/></Link>}{error&&<span className="small" role="alert">{ui(error)}</span>}</span>;}
