'use client';
/* Private authenticated image previews use the session-aware endpoint. */
/* eslint-disable @next/next/no-img-element */
import {ImagePicker} from './image-picker';
import {T} from "@/components/language-provider";

import {useLanguage} from './language-provider';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {AIRating,AISave} from './ai-output-tools';
import type {ReaderSource,AIOutput,Conversation} from '@/lib/ai/types';
export function ArticleAssistant({source,title,signedIn,returnPath,conversationId,initialOpen=false,general=false}:{source?:ReaderSource;title:string;signedIn:boolean;returnPath:string;conversationId?:string;initialOpen?:boolean;general?:boolean}){
 const {t:ui}=useLanguage();
 const {language}=useLanguage();
 const dialog=useRef<HTMLDialogElement>(null),end=useRef<HTMLDivElement>(null);const [open,setOpen]=useState(initialOpen),[conversation,setConversation]=useState<Conversation|null>(null),[messages,setMessages]=useState<AIOutput[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[question,setQuestion]=useState(''),[images,setImages]=useState<string[]>([]),[uploading,setUploading]=useState(false);
 useEffect(()=>{if(open&&!dialog.current?.open)dialog.current?.showModal();else if(!open&&dialog.current?.open)dialog.current.close();},[open]);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest',behavior:'smooth'});},[messages.length,busy]);
 async function send(mode='explain',text?:string,c=conversation){setBusy(true);setError('');try{const r=await fetch('/api/ai/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source,conversation_id:c?.id,expected_revision:c?.revision,language,mode,question:text,image_ids:images})}),d=await r.json();if(!r.ok)throw new Error(d.error);setConversation(d.conversation);setMessages(d.messages);setImages([]);if(text)setQuestion('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function start(mode='explain'){setOpen(true);setBusy(true);setError('');try{if(!conversationId&&source?.kind==='analysis'){try{await fetch('/api/news/'+source.id+'/context',{method:'POST'});}catch{/* Excerpt remains available when the full document cannot be reached. */}}const query=conversationId?'id='+conversationId:new URLSearchParams({kind:source!.kind,source_id:source!.id,language}).toString();const r=await fetch('/api/ai/chat?'+query),d=await r.json();if(!r.ok)throw new Error(d.error);setConversation(d.conversation);setMessages(d.messages||[]);if(conversationId||general){setBusy(false);}else await send(mode,undefined,d.conversation);}catch(e){setError((e as Error).message);setBusy(false);}}
 const initialized=useRef(false);useEffect(()=>{if(initialOpen&&!initialized.current){initialized.current=true;void start();} // Initial resume is a read-only fetch, never a generation.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[initialOpen]);
 return <div className="article-assistant" data-ai-ui="true"><div className="reader-actions">{signedIn?<><button className="button" disabled={busy} onClick={()=>void start('explain')}>{general?<T text="Open chat"/>:conversationId?<T text="Open conversation"/>:<T text="Explain article"/>}</button>{!conversationId&&!general&&<button className="button secondary" disabled={busy} onClick={()=>void start('translate')}><T text="Translate article"/></button>}</>:<Link className="button" href={'/login?next='+encodeURIComponent(returnPath)}><T text="Sign in for AI explanation"/></Link>}</div><p className="small">{conversationId?<T text="Reopen your saved conversation and continue asking."/>:<T text="A simple explanation of the available source, with room for follow-up questions. Google Gemini; free-tier input may be used by Google to improve its products."/>}</p>
 <dialog className={general?"ai-chat-drawer general-chat-drawer":"ai-chat-drawer"} ref={dialog} onClose={()=>setOpen(false)} onCancel={()=>setOpen(false)} aria-label={ui("Article AI conversation")}><header className="ai-chat-heading"><div><span className="eyebrow"><T text={general?"YOUR CLEARSTOCK ASSISTANT":"YOUR ARTICLE ASSISTANT"}/></span><h2><T text={general?"Ask anything, learn something.":"Understand it together."}/></h2></div><button type="button" className="text-button" aria-label={ui("Close AI conversation")} onClick={()=>setOpen(false)}>×</button></header>{!general&&<div className="ai-chat-reference"><span className="eyebrow"><T text="ARTICLE"/></span><strong>{conversation?.title||title}</strong></div>}<div className="ai-chat-toolbar">{conversation&&messages.length>0&&<><AISave key={conversation.id+String(conversation.saved)} id={conversation.id} kind="chat" initial={conversation.saved} onSaved={saved=>setConversation({...conversation,saved})}/><a className="small source" href={'/api/ai/conversations/'+conversation.id}><T text="Download chat ↗"/></a></>}</div>
 <div className="ai-chat-messages">{messages.map(m=><div className="ai-chat-exchange" key={m.id}><div className="chat-question"><span className="eyebrow"><T text="YOU"/></span><p>{ui(m.question||"Explain article")}</p>{!!m.source_snapshot.image_inputs?.length&&<div className="attachment-grid">{m.source_snapshot.image_inputs.map(i=><figure key={i.id}><img src={"/api/images?id="+i.id} alt={ui("Attached image")} loading="lazy"/></figure>)}</div>}</div><article className="chat-answer"><span className="eyebrow"><T text="GOOGLE GEMINI"/></span><p className={m.validation_error?"notice":"ai-answer"}>{m.validation_error?ui(m.validation_error):m.content.answer}</p><details className="small"><summary><T text="Source & generation details"/></summary><p>{m.source_snapshot.scope}</p>{m.content.citations.map(id=>{const e=m.source_snapshot.evidence.find(e=>e.id===id);return e?.url?<p key={id}><a className="source" href={e.url} target="_blank" rel="noopener noreferrer">{e.label} ↗</a></p>:<p key={id}>{e?.label}</p>;})}<a className="source" href={'/api/ai/outputs/'+m.id}><T text="Download this generation record ↗"/></a></details><div className="ai-output-footer"><span className="small">{m.language!==language&&<><T text="Historical answer · original language"/> · </>}{m.language==='en'?<T text="Requested English"/>:<T text="Requested 简体中文"/>}</span><AIRating outputId={m.id} initial={m.score}/></div></article></div>)}{busy&&<p className="small ai-chat-status" role="status"><T text="AI is reading the available context…"/></p>}{error&&<p className="notice" role="alert">{ui(error)}</p>}{!busy&&!messages.length&&!general&&<button className="button secondary" onClick={()=>conversationId?void start():void send()}><T text="Try again"/></button>}{general&&!busy&&!messages.length&&!error&&<p className="small">{ui("Ask a question about stocks, a screenshot, or any everyday topic. Current facts need a source; the assistant does not browse.")}</p>}<div ref={end}/></div>
 <form className="ai-chat-composer" onSubmit={e=>{e.preventDefault();if(question.trim())void send('explain',question.trim());}}><label htmlFor={'chat-question-'+(conversationId||source?.id)}><T text="Ask a follow-up"/></label><textarea id={'chat-question-'+(conversationId||source?.id)} rows={2} maxLength={1000} placeholder={ui(general?"Ask a question, or describe what you want to understand in the image…":"What does this mean? Give me a simpler example…")} value={question} onChange={e=>setQuestion(e.target.value)} disabled={busy||uploading||(!messages.length&&!general)}/><ImagePicker ids={images} onChange={setImages} max={1} disabled={busy} ai onBusy={setUploading}/><div className="section-title"><span className="small"><T text="Save keeps the whole conversation in Notebook."/></span><button className="button" disabled={busy||uploading||!question.trim()||(!messages.length&&!general)}><T text="Send"/></button></div></form></dialog></div>;
}
