'use client';
/* Private authenticated image previews use the session-aware endpoint. */
/* eslint-disable @next/next/no-img-element */
import {ImagePicker} from './image-picker';
import {T} from "@/components/language-provider";

import {useLanguage} from './language-provider';
import {useEffect,useRef,useState,type PointerEvent} from 'react';
import Link from 'next/link';
import {AIRating} from './ai-output-tools';
import type {ReaderSource,AIOutput,Conversation} from '@/lib/ai/types';
export function ArticleAssistant({source,title,signedIn,returnPath,conversationId,initialOpen=false,general=false,workspace=false,onConversation}:{source?:ReaderSource;title:string;signedIn:boolean;returnPath:string;conversationId?:string;initialOpen?:boolean;general?:boolean;workspace?:boolean;onConversation?:(conversation:Conversation)=>void}){
 const {t:ui}=useLanguage();
 const {language}=useLanguage();
 const dialog=useRef<HTMLDialogElement>(null),end=useRef<HTMLDivElement>(null);const [open,setOpen]=useState(initialOpen),[conversation,setConversation]=useState<Conversation|null>(null),[messages,setMessages]=useState<AIOutput[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[question,setQuestion]=useState(''),[images,setImages]=useState<string[]>([]),[uploading,setUploading]=useState(false),[width,setWidth]=useState(540),[expanded,setExpanded]=useState(false),[loading,setLoading]=useState(false);
 useEffect(()=>{if(workspace)return;if(open&&!dialog.current?.open)dialog.current?.showModal();else if(!open&&dialog.current?.open)dialog.current.close();},[open,workspace]);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest',behavior:'smooth'});},[messages.length,busy]);
 async function send(mode='explain',text?:string,c=conversation){setBusy(true);setError('');try{const r=await fetch('/api/ai/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source,conversation_id:c?.id,expected_revision:c?.revision,language,mode,question:text,image_ids:images})}),d=await r.json();if(!r.ok)throw new Error(d.error);setConversation(d.conversation);setMessages(d.messages);onConversation?.(d.conversation);if(!(general&&(!d.conversation||d.conversation.source_kind==='general')))setImages([]);if(text)setQuestion('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function start(mode='explain'){setOpen(true);setBusy(true);setLoading(true);setError('');try{if(!conversationId&&source?.kind==='analysis'){try{await fetch('/api/news/'+source.id+'/context',{method:'POST'});}catch{/* Excerpt remains available when the full document cannot be reached. */}}const query=conversationId?'id='+conversationId:new URLSearchParams({kind:source!.kind,source_id:source!.id,language}).toString();const r=await fetch('/api/ai/chat?'+query),d=await r.json();if(!r.ok)throw new Error(d.error);setConversation(d.conversation);setMessages(d.messages||[]);if(general&&d.conversation?.source_kind==='general')setImages(d.messages?.at(-1)?.source_snapshot?.image_inputs?.map((i:{id:string})=>i.id)||[]);setLoading(false);if(conversationId||general){setBusy(false);}else await send(mode,undefined,d.conversation);}catch(e){setError((e as Error).message);setLoading(false);setBusy(false);}}
 function resize(e:PointerEvent<HTMLDivElement>){e.currentTarget.setPointerCapture(e.pointerId);setExpanded(false);const initial=e.clientX,current=dialog.current?.clientWidth||width;const move=(event:globalThis.PointerEvent)=>setWidth(Math.max(360,Math.min(window.innerWidth,current+initial-event.clientX)));const finish=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',finish);};window.addEventListener('pointermove',move);window.addEventListener('pointerup',finish,{once:true});}
 const initialized=useRef(false);useEffect(()=>{if(initialOpen&&!initialized.current){initialized.current=true;void start();} // Initial resume is a read-only fetch, never a generation.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[initialOpen]);
 const content=<><header className="ai-chat-heading"><div><span className="eyebrow"><T text={general?"YOUR CLEARSTOCK ASSISTANT":"YOUR ARTICLE ASSISTANT"}/></span><h2>{workspace?(conversation?.title||ui("Your AI assistant")):<T text="Understand it together."/>}</h2></div>{!workspace&&<div className="drawer-controls"><button type="button" className="text-button" aria-label={ui(expanded?"Shrink chat":"Expand chat")} onClick={()=>setExpanded(!expanded)}>{expanded?"↙":"↗"}</button><button type="button" className="text-button" aria-label={ui("Minimize chat")} onClick={()=>setOpen(false)}>−</button><button type="button" className="text-button" aria-label={ui("Close AI conversation")} onClick={()=>setOpen(false)}>×</button></div>}</header>{(!general||(workspace&&conversation&&conversation.source_kind!=='general'))&&<div className="ai-chat-reference"><span className="eyebrow"><T text="ARTICLE"/></span><strong>{conversation?.title||title}</strong></div>}<div className="ai-chat-toolbar">{conversation&&messages.length>0&&<>{!workspace&&<Link className="small source" href={"/assistant?chat="+conversation.id}><T text="Open in Chat ↗"/></Link>}<a className="small source" href={'/api/ai/conversations/'+conversation.id}><T text="Download chat ↗"/></a></>}</div>
 <div className="ai-chat-messages">{messages.map(m=><div className="ai-chat-exchange" key={m.id}><div className="chat-question"><span className="eyebrow"><T text="YOU"/></span><p>{ui(m.question||"Explain article")}</p>{!!m.source_snapshot.image_inputs?.length&&<div className="attachment-grid">{m.source_snapshot.image_inputs.map(i=><figure key={i.id}><img src={"/api/images?id="+i.id} alt={ui("Attached image")} loading="lazy"/></figure>)}</div>}</div><article className="chat-answer"><span className="eyebrow"><T text="GOOGLE GEMINI"/></span><p className={m.validation_error?"notice":"ai-answer"}>{m.validation_error?ui(m.validation_error):m.content.answer}</p><details className="small"><summary><T text="Source & generation details"/></summary><p>{m.source_snapshot.scope}</p>{m.content.citations.map(id=>{const e=m.source_snapshot.evidence.find(e=>e.id===id);return e?.url?<p key={id}><a className="source" href={e.url} target="_blank" rel="noopener noreferrer">{e.label} ↗</a></p>:<p key={id}>{e?.label}</p>;})}<a className="source" href={'/api/ai/outputs/'+m.id}><T text="Download this generation record ↗"/></a></details><div className="ai-output-footer"><span className="small">{m.language!==language&&<><T text="Historical answer · original language"/> · </>}{m.language==='en'?<T text="Requested English"/>:<T text="Requested 简体中文"/>}</span><AIRating outputId={m.id} initial={m.score}/></div></article></div>)}{busy&&<p className="small ai-chat-status" role="status"><T text={loading?"Loading conversation…":"AI is reading the available context…"}/></p>}{error&&<p className="notice" role="alert">{ui(error)}</p>}{!busy&&!messages.length&&!general&&<button className="button secondary" onClick={()=>conversationId?void start():void send()}><T text="Try again"/></button>}{general&&!busy&&!messages.length&&!error&&<p className="small">{ui("Ask a question about stocks, a screenshot, or any everyday topic. Current facts need a source; the assistant does not browse.")}</p>}<div ref={end}/></div>
 <form className="ai-chat-composer" onSubmit={e=>{e.preventDefault();if(question.trim())void send('explain',question.trim());}}><label className={workspace?"sr-only":undefined} htmlFor={'chat-question-'+(conversationId||source?.id)}><T text="Ask a follow-up"/></label><textarea id={'chat-question-'+(conversationId||source?.id)} rows={2} maxLength={1000} placeholder={ui(general?"Ask a question, or describe what you want to understand in the image…":"What does this mean? Give me a simpler example…")} value={question} onChange={e=>setQuestion(e.target.value)} disabled={busy||uploading}/>{general&&(!conversation||conversation.source_kind==='general')?<><ImagePicker ids={images} onChange={setImages} max={1} disabled={busy} ai compact onBusy={setUploading}/>{!!images.length&&<p className="small"><T text="This image stays in context for follow-up questions. Remove it to stop using it."/></p>}</>:<Link className="small source" href="/assistant"><T text="Ask about an image in the AI assistant ↗"/></Link>}<div className="section-title"><span className="small"><T text="Chat history is saved automatically in Chat."/></span><button className="button" disabled={busy||uploading||!question.trim()}><T text="Send"/></button></div></form></>;
 return <div className={workspace?"assistant-canvas":"article-assistant"} data-ai-ui="true">{workspace?content:<><div className="reader-actions">{signedIn?<><button className="button" disabled={busy} onClick={()=>void start('explain')}><T text={conversationId?"Open conversation":"Explain article"}/></button></>:<Link className="button" href={'/login?next='+encodeURIComponent(returnPath)}><T text="Sign in for AI explanation"/></Link>}</div><dialog className="ai-chat-drawer" style={{width:expanded?'min(960px,100vw)':`min(${width}px,100vw)`}} ref={dialog} onClose={()=>setOpen(false)} onCancel={()=>setOpen(false)} aria-label={ui("Article AI conversation")}><div className="drawer-resize" role="separator" aria-label={ui("Resize chat")} aria-orientation="vertical" tabIndex={0} onPointerDown={resize} onKeyDown={e=>{if(e.key==='ArrowLeft'){e.preventDefault();setWidth(w=>Math.min(960,w+40));}if(e.key==='ArrowRight'){e.preventDefault();setWidth(w=>Math.max(360,w-40));}}}/>{content}</dialog></>}</div>;
}
