 'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {ArticleAssistant} from './article-assistant';
import {useLanguage} from './language-provider';
import type {Conversation} from '@/lib/ai/types';
type Summary=Pick<Conversation,'id'|'title'|'saved'|'source_kind'|'updated_at'>;
export function AssistantWorkspace({conversationId,newSourceId}:{conversationId?:string;newSourceId:string}){
 const {t}=useLanguage(),router=useRouter(),[history,setHistory]=useState<Summary[]>([]),[error,setError]=useState(''),[more,setMore]=useState(false),[busy,setBusy]=useState(false),[sidebar,setSidebar]=useState(true);
 async function load(offset=0){setBusy(true);try{const r=await fetch('/api/ai/chat?list=1&offset='+offset),d=await r.json();if(!r.ok)throw new Error(d.error);setHistory(old=>offset?[...old,...d.conversations]:d.conversations);setMore(d.more);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{let active=true;fetch('/api/ai/chat?list=1').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(active){setHistory(d.conversations);setMore(d.more);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 function changed(c:Conversation){setHistory(old=>[{id:c.id,title:c.title,saved:c.saved,source_kind:c.source_kind,updated_at:c.updated_at},...old.filter(x=>x.id!==c.id)]);if(!conversationId)router.replace('/assistant?chat='+c.id,{scroll:false});}
 return <section className={'assistant-workspace'+(sidebar?'':' sidebar-hidden')}><aside className="assistant-history"><header><h2>{t('Your chats')}</h2><button className="text-button" aria-label={t('Hide chat history')} onClick={()=>setSidebar(false)}>‹</button></header><button className="button secondary" onClick={()=>router.push('/assistant?new='+crypto.randomUUID())}>{t('New chat')} +</button><p className="small">{t('Private history · saved automatically')}</p><nav aria-label={t('Chat history')}>{history.map(c=><Link href={'/assistant?chat='+c.id} className={c.id===conversationId?'active':''} key={c.id}><strong>{c.title}</strong><small>{t(c.source_kind==='general'?'General chat':'Article chat')} · {new Date(c.updated_at).toLocaleDateString()}{c.saved?' · ★':''}</small></Link>)}</nav>{busy&&<p role="status" className="small">{t('Loading history…')}</p>}{!busy&&!history.length&&!error&&<p className="small">{t('Your conversations will appear here.')}</p>}{error&&<p role="alert" className="notice">{t(error)} <button className="text-button" onClick={()=>void load()}>{t('Try again')}</button></p>}{more&&<button className="text-button" disabled={busy} onClick={()=>void load(history.length)}>{t('Load more')}</button>}</aside><div className="assistant-main">{!sidebar&&<button className="history-toggle text-button" onClick={()=>setSidebar(true)}>{t('Show chat history')}</button>}<ArticleAssistant key={conversationId||newSourceId} source={{kind:'general',id:newSourceId}} title="Clearstock assistant" signedIn returnPath="/assistant" conversationId={conversationId} general workspace initialOpen onConversation={changed}/></div></section>;
}
