'use client';
import {T} from "@/components/language-provider";

import {useLanguage} from './language-provider';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {AISave,AIRating} from './ai-output-tools';
import type {AIOutput} from '@/lib/ai/types';
export function DailyAILearning({initial,day,signedIn,initialError=false,savedView=false}:{initial:AIOutput[];day:string;signedIn:boolean;initialError?:boolean;savedView?:boolean}){
 const {t:ui}=useLanguage();const {language}=useLanguage();const [lessons,setLessons]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(initialError?'Saved AI learning could not be loaded. Please try again.':'');const requested=useRef(false);
 async function generate(){setBusy(true);setError('');try{const r=await fetch('/api/ai/daily',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({language})}),d=await r.json();if(!r.ok)throw new Error(d.error);setLessons(d.lessons);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{if(signedIn&&!savedView&&!initialError&&!initial.length&&!requested.current){requested.current=true;void generate();} // Lazy daily generation: once when this user visits Learn; no background generation for inactive users.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[signedIn,savedView,initialError,initial.length]);
 return <section className="content-section daily-learning"><div className="section-title"><h2>{savedView?<T text="Saved AI articles"/>:<T text="Your five ideas for today"/>}</h2><span className="pill">{savedView?<T text="YOUR COLLECTION"/>:day+' · '+ui('New York time')}</span></div><p className="section-description">{savedView?<T text="Articles you starred, kept across days. Unsave an article to remove it from this view."/>:<T text="Five short AI explanations related to your saved terms, conversation topics and topics mentioned in your own notes. Topics already saved are excluded. Ratings help choose the next day’s topics and explanation style. One batch per day, generated when you visit; returning later reuses it."/>}</p>{!signedIn?<Link className="button" href="/login?next=%2Flearn"><T text="Sign in for your daily ideas"/></Link>:<>{!savedView&&!lessons.length&&<p className="small"><T text="Google Gemini receives saved term labels and saved chat titles. Only recognized topic labels from your own notes are sent; private note titles and bodies stay on the server. Free-tier input may be used by Google to improve its products."/></p>}{busy&&<div className="panel" role="status"><T text="Preparing your five explanations… This usually takes a few seconds."/></div>}{error&&<div className="panel notice" role="alert"><p>{ui(error)}</p>{!savedView&&<div className="reader-actions"><button className="button secondary" disabled={busy} onClick={()=>void generate()}><T text="Try again"/></button></div>}</div>}{savedView&&!lessons.length&&!error&&<div className="panel empty-state"><h3><T text="No saved AI articles yet."/></h3><p><T text="Save an article from Learn to keep it in Notebook."/></p><Link className="source" href="/learn"><T text="Explore today’s ideas →"/></Link></div>}<div className="cards ai-lesson-grid">{lessons.map(l=><article className="panel lesson-card" key={l.id}><span className="eyebrow"><T text="AI LEARNING EXPLANATION"/></span><h3><Link href={'/learn/ai/'+l.id}>{l.content.title}</Link></h3><p>{l.content.answer.slice(0,160)}{l.content.answer.length>160?'…':''}</p><div className="ai-lesson-actions"><Link className="source" href={'/learn/ai/'+l.id}><T text="Read explanation →"/></Link><AISave id={l.id} kind="lesson" initial={l.saved} onSaved={saved=>{if(savedView&&!saved)setLessons(items=>items.filter(i=>i.id!==l.id));}}/></div><div className="ai-output-footer"><span className="small">{l.language==='en'?<T text="English"/>:'简体中文'}</span><AIRating outputId={l.id} initial={l.score}/></div></article>)}</div></>}</section>;}
