'use client';
import {T} from "@/components/language-provider";

import {useEffect,useState} from 'react';
import {useLanguage} from './language-provider';
import {LiveQuote} from './live-market';
import type {Price} from '@/lib/market/types';
type Context={market?:Price;document?:{url:string;char_count:number;sha256:string;retrieved_at:string};source_url?:string;document_error?:boolean};
export function EvidenceContext({analysisId,ticker,signedIn}:{analysisId:string;ticker:string;signedIn:boolean}){const {t}=useLanguage(),[data,setData]=useState<Context>({}),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{const controller=new AbortController();void fetch('/api/news/'+analysisId+'/context',{signal:controller.signal}).then(r=>r.ok?r.json():{}).then(setData).catch(()=>{});return()=>controller.abort();},[analysisId]);return <section className="panel current-evidence" data-ai-ui="true"><h2>{t('Current data context')}</h2><p className="small">{t('The original analysis used an earlier source snapshot. New AI explanations use the current market and source context below.')}</p><LiveQuote ticker={ticker} initial={data.market}/>{data.document?<><p><strong>{t('Full SEC original cached')}</strong> · {data.document.char_count.toLocaleString()} {t('characters')}</p><p className="small">{t('AI uses retrieved passages from the complete cached document.')}</p><details className="small"><summary><T text="SHA256"/></summary>{data.document.sha256}</details></>:<><p className="small">{t('Only the saved excerpt is available until the official document is prepared.')}</p>{signedIn&&data.source_url&&<button className="button secondary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const r=await fetch('/api/news/'+analysisId+'/context',{method:'POST'}),d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);if(d.document_error)throw new Error('SEC document is temporarily unavailable. The saved excerpt remains usable.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{t(busy?'Preparing source…':'Prepare full SEC source')}</button>}</>}{data.source_url&&<p><a className="source" target="_blank" rel="noopener noreferrer" href={data.source_url}>{t('Open source ↗')}</a></p>}{error&&<p role="alert">{t(error)}</p>}</section>;}
