 'use client';
import {useLanguage} from './language-provider';
import {useState,useEffect} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
export function NewsRefresh({signedIn}:{signedIn:boolean}){
 const {t}=useLanguage(),router=useRouter(),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[failures,setFailures]=useState<string[]>([]),[remaining,setRemaining]=useState(0),[checked,setChecked]=useState<string|null>(null);
 useEffect(()=>{if(!signedIn)return;let active=true;fetch('/api/news/refresh').then(r=>r.json()).then(d=>{if(active){setRemaining(d.retry_after||0);setChecked(d.last_checked||null);}}).catch(()=>{});return()=>{active=false;};},[signedIn]);
 useEffect(()=>{if(!remaining)return;const id=setTimeout(()=>setRemaining(n=>Math.max(0,n-1)),1000);return()=>clearTimeout(id);},[remaining]);
 async function update(){setBusy(true);setMessage('');setFailures([]);try{const r=await fetch('/api/news/refresh',{method:'POST'}),d=await r.json();setRemaining(d.retry_after||0);if(d.last_checked)setChecked(d.last_checked);if(!r.ok){if(d.failed_sources){setFailures(d.failed_sources);setMessage('Sources are temporarily unavailable. Previously saved news remains visible.');}else setMessage(d.error||'News is temporarily unavailable.');return;}setFailures(d.failed_sources||[]);setMessage('News checked: {count} source records refreshed.'.replace('{count}',String(d.available)));router.refresh();}catch{setMessage('The update could not finish. Please try again later.');}finally{setBusy(false);}}
 return <div className="news-refresh"><div className="reader-actions">{signedIn?<button className="button secondary" disabled={busy||remaining>0} onClick={()=>void update()}>{t(busy?'Checking official sources…':'↻ Update news')}{!busy&&remaining>0&&` · ${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`}</button>:<Link className="source" href="/login?next=%2Fnews">{t('Sign in to update news ↗')}</Link>}</div><p className="small">{t('One shared news refresh per 10 minutes. Automatic scheduled updates are not enabled yet.')}</p>{checked&&<p className="small">{t('Last checked')} · {new Date(checked).toLocaleString()}</p>}{message&&<p className="small notice" role="status">{t(message)}</p>}{failures.length>0&&<p className="small" role="status">{t('Temporarily unavailable sources')}: {failures.join(', ')}. {t('Other source updates were saved. Earlier reports remain visible.')}</p>}</div>;
}
