'use client';
import {lookupVocabulary} from '@/lib/market/vocabulary.mjs';
import {T} from "@/components/language-provider";

import {useLanguage} from './language-provider';
import {useEffect,useState,useRef} from 'react';
import Link from 'next/link';
import {BookmarkButton} from './bookmark-button';
import {AIRating,AISave} from './ai-output-tools';
import type {ReaderSource,AIOutput} from '@/lib/ai/types';
type Choice={text:string;definition:string;provenance:string;selection:{concept?:string;analysis_id?:string;section?:string;index?:number};saved?:boolean};
export function TextSelectionHelper({choices=[],signedIn,returnPath,source}:{choices?:Choice[];signedIn:boolean;returnPath:string;source?:ReaderSource}){
 const {t:ui}=useLanguage();
 const {language}=useLanguage();
 const [forceAI,setForceAI]=useState(false),[selected,setSelected]=useState(''),[choice,setChoice]=useState<Choice|null>(null),[output,setOutput]=useState<AIOutput|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[mode,setMode]=useState('explain'),[retry,setRetry]=useState(0),[position,setPosition]=useState({left:16,top:120});const box=useRef<HTMLElement>(null),lastSelection=useRef('');
 const quick=selected&&!forceAI?lookupVocabulary(selected,language):null;
 const sourceKind=source?.kind,sourceId=source?.id;
 useEffect(()=>{const update=(event:Event)=>{if(event.target instanceof Element&&(box.current?.contains(event.target)||event.target.closest('[data-ai-ui]')))return;const selection=window.getSelection(),node=selection?.anchorNode,element=node?.parentElement;if(!selection||!element?.closest('[data-readable="true"]')||element.closest('input,textarea,button,select')||!selection.rangeCount)return;const text=selection.toString().trim().replace(/\s+/g,' ');if(!text||text.length>160||text===lastSelection.current)return;lastSelection.current=text;const rect=selection.getRangeAt(0).getBoundingClientRect();setPosition({left:Math.max(12,Math.min(rect.left,window.innerWidth-392)),top:Math.max(12,Math.min(rect.bottom+12,window.innerHeight-400))});setSelected(text);setForceAI(false);setOutput(null);setError('');setChoice(choices.find(c=>c.text.toLowerCase()===text.toLowerCase())||null);};document.addEventListener('mouseup',update);document.addEventListener('keyup',update);return()=>{document.removeEventListener('mouseup',update);document.removeEventListener('keyup',update);};},[choices]);
 useEffect(()=>{if(!selected||!signedIn||!sourceKind||!sourceId||!!lookupVocabulary(selected,language)&&!forceAI)return;const controller=new AbortController();const timer=setTimeout(async()=>{setBusy(true);setOutput(null);setError('');try{const r=await fetch('/api/ai/explain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source:{kind:sourceKind,id:sourceId},text:selected,mode,language}),signal:controller.signal});const d=await r.json();if(!r.ok)throw new Error(d.error);setOutput(d.output);}catch(e){if(!controller.signal.aborted)setError((e as Error).message);}finally{if(!controller.signal.aborted)setBusy(false);}},400);return()=>{clearTimeout(timer);controller.abort();};},[selected,signedIn,sourceKind,sourceId,mode,language,retry,forceAI]);
 if(!selected)return null;
 return <aside ref={box} data-ai-ui="true" className="selection-helper panel ai-selection" style={{left:position.left,top:position.top,maxHeight:`calc(100dvh - ${position.top}px - 12px)`}} aria-label={ui("Selected text AI explanation")}><button className="text-button selection-close" aria-label={ui("Close selected term")} onClick={()=>{setSelected('');lastSelection.current='';}}>×</button><span className="eyebrow">{quick?<T text="QUICK GLOSSARY"/>:source?<T text="AI EXPLANATION"/>:<T text="SELECTED TEXT"/>}</span><h3>{selected}</h3>{source&&<div className="reader-options"><div className="segmented-control"><button type="button" className={mode==='explain'?'active':''} onClick={()=>setMode('explain')}><T text="Explain"/></button><button type="button" className={mode==='translate'?'active':''} onClick={()=>setMode('translate')}><T text="Translate"/></button></div></div>}
 {quick?<><p>{mode==='translate'?quick.term+': ':''}{quick.definition}</p><p className="small"><T text="Reviewed glossary · instant · no AI quota used"/></p><BookmarkButton key={quick.source_key} selection={{...quick.selection,text:selected}} signedIn={signedIn} returnPath={returnPath}/>{source&&signedIn&&<button type="button" className="text-button" onClick={()=>setForceAI(true)}><T text="Ask AI in context"/></button>}</>:!signedIn?<><p><T text="Sign in for a short AI explanation or translation."/></p><Link className="button" href={'/login?next='+encodeURIComponent(returnPath)}><T text="Sign in to explain"/></Link></>:source?<>{busy&&<p className="small" role="status"><T text="Explaining in context…"/></p>}{error&&<><p className="small" role="alert">{ui(error)}</p><button className="text-button" onClick={()=>setRetry(retry+1)}><T text="Try again"/></button></>}{output&&<><p className="ai-answer" key={output.id}>{output.content.answer}</p><div className="ai-output-footer"><AISave key={'save'+output.id} id={output.id} kind="term" initial={output.saved}/><AIRating key={'rating'+output.id} outputId={output.id} initial={output.score}/></div><a className="small source" href={'/api/ai/outputs/'+output.id}><T text="Generation record ↗"/></a></>}<p className="ai-provider-note"><T text="Google Gemini · Uses this article’s available context. Select text to request an explanation; free-tier input may be used by Google to improve its products."/></p></>:choice?<><p>{choice.definition}</p><BookmarkButton selection={choice.selection} signedIn={signedIn} returnPath={returnPath}/></>:<p><T text="Select text from an article to get its AI explanation."/></p>}</aside>;
}
