import sharp from 'sharp';
import {createHash} from 'node:crypto';
import {HttpError} from '@/lib/news/api';
import {UUID} from '@/lib/news/validation.mjs';
import type {SupabaseClient} from '@supabase/supabase-js';
export function imageIds(value:unknown,max=3):string[]{if(value===undefined)return [];if(!Array.isArray(value)||value.length>max||value.some(id=>typeof id!=='string'||!UUID.test(id))||new Set(value).size!==value.length)throw new HttpError(400,'Choose valid images.');return value;}
export async function ownedImages(s:SupabaseClient,owner:string,ids:string[]){if(!ids.length)return [];const {data,error}=await s.from('user_images').select('id,storage_path,sha256,mime_type,width,height,byte_size').eq('owner_id',owner).eq('status','ready').in('id',ids);if(error||data?.length!==ids.length)throw new HttpError(404,'Image unavailable.');return ids.map(id=>data.find(i=>i.id===id)!);}
export async function normalizeImage(bytes:Buffer){try{const img=sharp(bytes,{limitInputPixels:20000000,animated:false,failOn:'warning'}),meta=await img.metadata();if(!['png','jpeg','webp'].includes(meta.format||'')||(meta.pages||1)>1)throw new Error();const {data,info}=await img.rotate().resize({width:1600,height:1600,fit:'inside',withoutEnlargement:true}).webp({quality:78}).toBuffer({resolveWithObject:true});if(data.length>1500000)throw new Error();return {bytes:data,sha256:createHash('sha256').update(data).digest('hex'),width:info.width,height:info.height,byte_size:data.length};}catch{throw new HttpError(400,'Use a valid PNG, JPEG or WebP image under 2 MB.');}}
export async function imageParts(s:SupabaseClient,images:Awaited<ReturnType<typeof ownedImages>>){return Promise.all(images.map(async i=>{const {data,error}=await s.storage.from('notebook-images').download(i.storage_path);if(error||!data)throw new HttpError(503,'Image could not be read.');const bytes=Buffer.from(await data.arrayBuffer());if(createHash('sha256').update(bytes).digest('hex')!==i.sha256)throw new HttpError(503,'Image integrity check failed.');return {inline_data:{mime_type:i.mime_type,data:bytes.toString('base64')}};}));}
